import Head from "next/head";
import Link from "next/link";
export default function Home() {
  return (
    <div className="container mx-auto">
      <Head>
        <title>WhatIBuilt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="px-3 flex flex-row justify-between my-2 py-3 ">
        <Link className="text-zinc-800 font-serif font-bold text-2xl" href="/">
          WhatIBuilt
        </Link>
        <ul className="flex flex-row justify-between items-center gap-x-4">
          <li className="px-4 py-2 border rounded-lg text-sm">
            <Link href="/auth/login">Login</Link>
          </li>
          <li className="md:px-10 px-3 py-2 border rounded-lg bg-primary text-zinc-100 text-sm">
            <Link href="/auth/register">Sign up</Link>
          </li>
        </ul>
      </nav>

      <section className="w-screen h-[500px] flex flex-col justify-center items-center text-zinc-900">
        <h1 className="text-8xl font-bold my-1">Build it.</h1>
        <h1 className="text-8xl font-bold my-1">Publish.</h1>
        <h1 className="text-8xl font-bold my-1">Simple.</h1>
      </section>
    </div>
  );
}
