import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
export default function Home() {
  return (
    <div className="mx-auto dark:bg-background min-h-screen">
      <Head>
        <title>WhatIBuilt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="px-3 flex flex-row justify-between py-3 items-center">
        <Link
          className="dark:text-zinc-200 text-zinc-800 font-serif font-bold text-lg"
          href="/"
        >
          WhatIBuilt
        </Link>
        <ul className="flex flex-row justify-between items-center gap-x-4">
          <li className="px-4 py-2 hover:bg-primary hover:text-zinc-200 rounded-lg text-sm">
            <Link href="/auth/login">Login</Link>
          </li>
        </ul>
      </nav>

      <section className="w-screen md:mt-52 mt-32 flex  flex-col justify-center items-center dark:text-zinc-200 text-zinc-900 gap-y-3 text-center">
        <h1 className="md:text-8xl sm:text-6xl text-7xl font-extrabold my-1 text-center flex flex-col md:flex-row ">
          <span>Build it.</span> <span className="text-primary">Publish.</span>
          <span>Simple.</span>
        </h1>
        <p className="text-center px-10">
          You can create a dev porfolio with so much ease. Put all your content
          from different platforms in one place
        </p>
        <Link
          href="/auth/login"
          className="from-background via-background to-primary text-zinc-200 px-10 py-2 rounded-lg shadow bg-gradient-to-br hover:from-primary hover:via-background hover:to-background transition-all duration-700 w-56 dark:from-primary dark:via-primary dark:to-background"
        >
          Create porfolio
        </Link>
      </section>
    </div>
  );
}
